# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainwin(object):
    def setupUi(self, mainwin):
        mainwin.setObjectName("mainwin")
        mainwin.resize(811, 621)
        self.centralwidget = QtWidgets.QWidget(mainwin)
        self.centralwidget.setObjectName("centralwidget")
        self.btn = QtWidgets.QPushButton(self.centralwidget)
        self.btn.setGeometry(QtCore.QRect(10, 10, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn.setFont(font)
        self.btn.setObjectName("btn")
        mainwin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainwin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 811, 21))
        self.menubar.setObjectName("menubar")
        mainwin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainwin)
        self.statusbar.setObjectName("statusbar")
        mainwin.setStatusBar(self.statusbar)

        self.retranslateUi(mainwin)
        QtCore.QMetaObject.connectSlotsByName(mainwin)

    def retranslateUi(self, mainwin):
        _translate = QtCore.QCoreApplication.translate
        mainwin.setWindowTitle(_translate("mainwin", "YellowCircles"))
        self.btn.setText(_translate("mainwin", "Нарисовать\n"
"окружности"))
